name: Deploy Vanya

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519_vanya
          chmod 600 ~/.ssh/id_ed25519_vanya
          ssh-keyscan -H 45.150.11.85 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519_vanya nick@45.150.11.85 << 'EOF'
            cd ~/vanya
            git pull origin main
            source .venv/bin/activate
            sudo systemctl restart vanya || systemctl restart vanya          
          EOF
